@startuml
    hide footbox
        autonumber

        actor "User" as U
        participant ":Visualization" as SPA
        participant ":change-profile.component" as UC
        participant ":UserService" as US

        activate U
            U -> SPA : Fills the requested data needed for the change profile
            activate SPA
            SPA -> UC : changeProfile(email, phoneNumber, password, birthDate, name, tag)
            activate UC
            UC -> US : updateProfile(updatedUserDTO)
            activate US
            US ->o empty : HTTP request (put)
            empty o--> US : userDTO(Creates userDTO/Bad request)
            deactivate US
            deactivate UC
            SPA --> U : informs the succeed of the operation
            deactivate SPA
        deactivate U